"""added new fields to job postings

Revision ID: 2e7b05bd539d
Revises: 6e7dde46b210
Create Date: 2024-03-19 22:50:43.626983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7b05bd539d'
down_revision = '6e7dde46b210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.drop_column('location')
        batch_op.drop_column('company')

    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
