"""coverletter vanilla table

Revision ID: 8655e2ee3de0
Revises: 
Create Date: 2024-03-10 23:20:01.333352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8655e2ee3de0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('stop_sequence', sa.String(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('grounding_source', sa.String(), nullable=True),
    sa.Column('logprobs', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('postings',
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('posting_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('prompts',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.posting_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('resume_items',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ),
    sa.PrimaryKeyConstraint('resume_id', 'title')
    )
    with op.batch_alter_table('resume_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_items_category'), ['category'], unique=False)

    op.create_table('cover_letters',
    sa.Column('cover_letter_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['model_configs.config_id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.prompt_id'], ),
    sa.PrimaryKeyConstraint('cover_letter_id')
    )
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letters_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_timestamp'))

    op.drop_table('cover_letters')
    with op.batch_alter_table('resume_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_items_category'))

    op.drop_table('resume_items')
    op.drop_table('prompts')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('postings')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
