"""empty message

Revision ID: e9ba5e7a5ed0
Revises: 
Create Date: 2024-03-13 22:49:28.806357

"""

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = "e9ba5e7a5ed0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created",
                sa.DateTime(),
                nullable=False,
                server_default=str(datetime.now(timezone.utc)),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_column("created")

    # ### end Alembic commands ###
